# import torch
# import torch.nn as nn
# from torchvision.transforms import Compose, CenterCrop
# from pytorchvideo.transforms import (
#     ApplyTransformToKey,
#     UniformTemporalSubsample,
#     Normalize,
#     RandomShortSideScale,
# )
# from pytorchvideo.data.encoded_video import EncodedVideo
# from pytorchvideo.models.hub import x3d_s

# # ======================
# # CONFIG
# # ======================

# MODEL_PATH = r"D:\Vertex_AI\Model\x3d_s_best.pth"
# VIDEO_PATH = r"D:\Vertex_AI\test_data\vid.mp4"   
# NUM_CLASSES = 3
# CLIP_DURATION = 1.0
# DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# CLASS_NAMES = ["backhand_good", "forehand_good", "serve_good"]


# # ======================
# # LOAD MODEL
# # ======================

# model = x3d_s(pretrained=False)
# model.blocks[-1].proj = nn.Linear(
#     model.blocks[-1].proj.in_features,
#     NUM_CLASSES
# )

# model.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))
# model = model.to(DEVICE)
# model.eval()

# print("✅ Model loaded successfully")


# # ======================
# # TRANSFORM (Same as validation)
# # ======================

# transform = ApplyTransformToKey(
#     key="video",
#     transform=Compose([
#         UniformTemporalSubsample(16),
#         RandomShortSideScale(min_size=160, max_size=160),
#         CenterCrop(160),  # ✅ use CenterCrop for inference
#         Normalize((0.45, 0.45, 0.45), (0.225, 0.225, 0.225)),
#     ]),
# )


# # ======================
# # LOAD VIDEO
# # ======================

# video = EncodedVideo.from_path(VIDEO_PATH)

# clip = video.get_clip(start_sec=0, end_sec=CLIP_DURATION)
# clip = transform(clip)

# inputs = clip["video"].unsqueeze(0).to(DEVICE)  # Add batch dimension


# # ======================
# # INFERENCE
# # ======================

# with torch.no_grad():
#     outputs = model(inputs)
#     probabilities = torch.softmax(outputs, dim=1)
#     print("✅ Model inference completed successfully")
#     print("✅ Raw model outputs:", outputs)
#     confidence, predicted_class = torch.max(probabilities, 1)
# print("✅ Inference completed successfully")
# print("✅ Predicted class index:", predicted_class.item())
# print("✅ Confidence score:", confidence.item())
# predicted_label = CLASS_NAMES[predicted_class.item()]

# print("\n🎯 Prediction Results:")
# print("Predicted Class :", predicted_label)
# print("Confidence      :", round(confidence.item() * 100, 2), "%")

import json
import torch
import torch.nn as nn
from torchvision.transforms import Compose, CenterCrop
from pytorchvideo.transforms import (
    ApplyTransformToKey,
    UniformTemporalSubsample,
    Normalize,
    RandomShortSideScale,
)
from pytorchvideo.data.encoded_video import EncodedVideo
from pytorchvideo.models.hub import x3d_s


# ======================
# CONFIG
# ======================

MODEL_PATH     = r"D:\Vertex_AI\video_engine\x3d_s_best.pth"
VIDEO_PATH     = r"D:\Vertex_AI\test_data\vid_92.mp4"
CLASS_MAP_PATH = r"class_names.json"    # auto-generated by training script

NUM_CLASSES   = 3
CLIP_DURATION = 2.5     # must match training
NUM_FRAMES    = 13      # X3D-S paper: 13 frames — must match training
SPATIAL_SIZE  = 160     # X3D-S paper: 160 x 160 — must match training

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"


# ======================
# LOAD CLASS NAMES
# (from JSON saved during training — guaranteed correct order)
# ======================

with open(CLASS_MAP_PATH) as f:
    label_map = json.load(f)

CLASS_NAMES = [label_map[str(i)] for i in range(NUM_CLASSES)]
print("Class mapping:", CLASS_NAMES)


# ======================
# LOAD MODEL — X3D Small
# ======================

model = x3d_s(pretrained=False)
model.blocks[-1].proj = nn.Linear(
    model.blocks[-1].proj.in_features,
    NUM_CLASSES
)

model.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))
model = model.to(DEVICE)
model.eval()

print("✅ Model loaded successfully")


# ======================
# TRANSFORM
# (Must be identical to val_transform used in training)
# ======================

transform = ApplyTransformToKey(
    key="video",
    transform=Compose([
        UniformTemporalSubsample(NUM_FRAMES),
        RandomShortSideScale(min_size=SPATIAL_SIZE, max_size=SPATIAL_SIZE),
        CenterCrop(SPATIAL_SIZE),       # ✅ CenterCrop for inference (deterministic)
        Normalize((0.45, 0.45, 0.45), (0.225, 0.225, 0.225)),
    ]),
)


# ======================
# LOAD & PREPROCESS VIDEO
# ======================

video = EncodedVideo.from_path(VIDEO_PATH)
clip  = video.get_clip(start_sec=0, end_sec=CLIP_DURATION)
clip  = transform(clip)

inputs = clip["video"].unsqueeze(0).to(DEVICE)   # add batch dimension


# ======================
# INFERENCE
# ======================

with torch.no_grad():
    outputs       = model(inputs)
    probabilities = torch.softmax(outputs, dim=1)

confidence, predicted_idx = torch.max(probabilities, 1)
predicted_label = CLASS_NAMES[predicted_idx.item()]

# Print all class probabilities for full transparency
print("\n📊 All class probabilities:")
for i, name in enumerate(CLASS_NAMES):
    print(f"   {name:20s}: {probabilities[0][i].item()*100:.2f}%")

print("\n🎯 Prediction Results:")
print(f"   Predicted Class : {predicted_label}")
print(f"   Confidence      : {round(confidence.item() * 100, 2)} %")